import { Rate } from "./types/rate";

export const sampleProducts: Rate[] = [
  {
    name: "Agboola Ifedayo",
    alias: "black_scripts",
    slug: "agboola-ifedayo",
    image: "../images/p1.jpg",
    currency: "€",
    rate: 1720,
    amount: 2000,
    note: "I have €2,000 and I am willing to exchange it to naira for a very cheap rate",
    userRating: 5,
  },
  {
    name: "Oke Damilola",
    alias: "black_scripts",
    slug: "agboola-ifedayo",
    image: "../images/p1.jpg",
    currency: "£",
    rate: 1720,
    amount: 2000,
    note: "I have £2,000 and I am willing to exchange it to naira for a very cheap rate",
    userRating: 5,
  },
  {
    name: "Agboola Ifedayo",
    alias: "black_scripts",
    slug: "agboola-ifedayo",
    image: "../images/p1.jpg",
    currency: "₦",
    rate: 1720,
    amount: 2000,
    note: "I have ₦2,000 and I am willing to exchange it to naira for a very cheap rate",
    userRating: 5,
  },
  {
    name: "Agboola Ifedayo",
    alias: "black_scripts",
    slug: "agboola-ifedayo",
    image: "../images/p1.jpg",
    currency: "$",
    rate: 1720,
    amount: 2000,
    note: "I have $2,000 and I am willing to exchange it to naira for a very cheap rate",
    userRating: 5,
  },
];
